### ISSUE TITLE
Add a testing system

### ISSUE THREAD

**Issue by BBasile** [dlang-community/dsymbol#19]
It's hard to fix problems in DCD that are related to DSymbol.

**Comment by ANtlord** [comment]
@BBasile
Can not this script [described](https://github.com/Hackerpilot/dsymbol/issues/14#issuecomment-287536792) by you used for testing, because it depends on libdparse?

**Comment by BBasile** [comment]
It could to the extent that dependencies are properly tagged (so that latest version is always on code.dlang.org) . Dependencies are automatically handled by DUB (the first comment is like a description). For now even without the git tags this would work (because `~master` is still allowed by DUB).

Tests could also not be based on DUB but rather on libdparse and EMSI containers as git submodule (and then some shell scripts / makfile to launch them).

Finally another option is to use DUB but not to fetch from code.dlang.org. Dependencies can be located with a relative path (like [here](https://github.com/BBasile/kheops/blob/master/runnable/actions_window.d#L5))

**Comment by ANtlord** [comment]
Info about using scripts running by dub is clear for me now. Thank you)
@BBasile 
What do you mean saying "testing system"? Is it not a usual set of unit tests? Do you mean something like tests from DCD project?

**Comment by ANtlord** [comment]
I suppose implementation of unit tests is huge work. But it is possble to create high level unit tests for largest structures and functions?

BTW, do we have coverage tools for D?

**Comment by BBasile** [comment]
Initially I was thinking to smthg like DCD but now I realize that a module with some unittest blocks would probably be enough.In this module each test would use helpers to parse a code and returns a DSymbol (like the first part of my script). The test would then verify the structure.

That being said you probably need to understand the whole library if you want to add a test system. With what's been made the other day I can say that it's not my case...There's more auto array (and auto assoc array that still don't work)

**Comment by SSoulaimane** [comment]
after chasing the #36 bug a bit it seems the source of the problem is here [symbol.d:347](https://github.com/dlang-community/dsymbol/blob/master/src/dsymbol/symbol.d#L347) the `parts` field is a binary search tree and here [symbol.d:204](https://github.com/dlang-community/dsymbol/blob/master/src/dsymbol/symbol.d#L204) the sorting is done by `name` field pointers for a more efficient search. this unfortunately renders anything that relies on the order of the _parts_ symbols unreliable. including the current test system. It needs some fixing.

other code may be affected by this bug, for instance I was also relying on the order of the _parts_ symbols in my work on ufcs for dcd, for checking the first parameter, and noticed after a bit of debugging that the arguments were sometimes disordered. I think I'll use `argNames` field to get the order correct.
