### ISSUE TITLE
The replacement?

### ISSUE THREAD

**Issue by ANtlord** [dlang-community/dsymbol#38]
Hello!

Recently we got ddmd as a library. Now we have a parser is used by DMD. Is it relevant to replace dsymbol by ddmd? Or maybe can we use it to get some abilities? I understand how the replacement is great but ddmd give a syncronization with D language features and it is supported by a huge part of the community.

Thoughts?

Sorry if my english is not clear.

**Comment by Hackerpilot** [comment]
It does make sense, however in the past having a second parser implementation has been useful for finding errors in the official language specification. https://issues.dlang.org/show_bug.cgi?id=10233

**Comment by BBasile** [comment]
Memory management makes the "replacement" more than hypothetical, at least for DCD.

**Comment by ANtlord** [comment]
> https://issues.dlang.org/show_bug.cgi?id=10233
OMG. So complex bug.
> Memory management makes the "replacement" more than hypothetical, at least for DCD.
I can't get what you mean. Are Data structures used in dsymbol more preferred to use in DCD?

**Comment by rikkimax** [comment]
The frontend inside dmd at this current point in time is not able to be used as a library. It is one shot per process (and last I tried can't be compiled separately on all platforms).
So this is fairly open and shut issue.

A lot more work needs to go into it before we will see it being used in tooling.

**Comment by ANtlord** [comment]
I can't understand. Please, anyone, provide a link with information about issues of the ddmd library.

**Comment by rikkimax** [comment]
Basically there is a very wide range of assumptions strewn all throughout the dmd codebase. All of which were made for a single run per executable execution. In other words, you don't create a compiler object and run it. You create the process and then run it. Can't be reset, that is all it supports.

It is fairly simple, it just wasn't designed to be used this way and it will take a LOT of hard work to get it anywhere close to desirable for library usage. There are no links to reference, because nobody can use it as it stands for what you're suggesting. Nor has anybody tried as far as I'm aware. It just isn't there yet. Those that do work on it, tend to you know make PR's to get it closer to the goal post, instead of writing about it.

**Comment by ANtlord** [comment]
Got it. I understand a feature PR is better than writing about the feature. It is a suggestion to know a direction of the project.
